[phases.setup]
nixPkgs = ["python312", "glib", "mesa"]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0"]

[phases.install]
cmds = [
  "python3 -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt -c constraints.txt"
]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"